### ISSUE TITLE
Patches for libvirt-php

### ISSUE THREAD

**Issue by inode64** [yzslab/php-libvirt-client#4]
Only 0001-Add-function-libvirt_domain_undefine_flags-and-libvi.patch and 0003-Add-error-code-and-error-domain-support.patch   is for libvirt-php-0.5.5 

¿What version do make you 0002-Add-libvirt_domain_reset-to-support-virDomainReset.patch?

I think make a tree for patches different versions of libvirt-php 
/libvirt-php-patches
/libvirt-php-patches/0.5.3/
/libvirt-php-patches/0.5.4/
/libvirt-php-patches/0.5.5/
etc..

**Comment by yzslab** [comment]
Hi, 
These patches are based on commit 8626cb017de0a564fa95f5db0c71981a20319540: https://libvirt.org/git/?p=libvirt-php.git;a=commit;h=8626cb017de0a564fa95f5db0c71981a20319540

The README section #use-patch descriptes these steps: https://github.com/yzslab/php-libvirt-client#use-patch

**Comment by inode64** [comment]
I make a stub for libvirt-php to phpstorm
I included your functions too

https://github.com/JetBrains/phpstorm-stubs/pull/1083

**Comment by yzslab** [comment]
Hi, thanks, i think this issue can be closed now.

**Comment by inode64** [comment]
Please, You send the patches of your project https://github.com/yzslab/libvirt-php to https://gitlab.com/libvirt/libvirt-php

**Comment by yzslab** [comment]
> Please, You send the patches of your project https://github.com/yzslab/libvirt-php to https://gitlab.com/libvirt/libvirt-php

I sent a patche two years ago: https://listman.redhat.com/archives/libvir-list/2019-February/msg01118.html, but seems that the libvirt-php maintainers didn't notice it, so i gave up sending patches and created a forked version.

**Comment by yzslab** [comment]
> Please, You send the patches of your project https://github.com/yzslab/libvirt-php to https://gitlab.com/libvirt/libvirt-php

Oh, i suddenly noticed that they accept merge request on gitlab after May 2020: https://github.com/libvirt/libvirt-php/commit/db587a59c07db27ab2408959023a1d3489ae652d
I will try to create a merge request to their gitlab project, thanks.
