### ISSUE TITLE
 How to create get functions

### ISSUE THREAD

**Issue by inode64** [yzslab/php-libvirt-client#6]
I am thinking of adding support not only to add devices but to be able to obtain parameters of the current domains and be able to modify them without having to create a new domain.
It is by integrating it into your code structure so that you keep as little as possible.
Attached an example of how it could be

Thanks for your help. All the best

-----------------------
<pre>
<?php

require_once __DIR__ . '/vendor/autoload.php';

use YunInternet\Libvirt\Connection;
use YunInternet\Libvirt\Configuration\Domain;

$connection = new Connection("qemu+ssh://test/system");

$dom = $connection->domainLookupByName('example');

$domainXML = $dom->getDomain();

$disk = $domainXML->device()->getDisk('vda'); // get values of this disk in actual domain

$domainXML->device() // add new disk
            ->addDisk("volume", "disk", function (Domain\Device\Disk $disk) {
                $disk
                    ->volumeSource("testPool1", "testVolume1")
                    ->setDriverType("qcow2")
                    ->setTargetBus("virtio")
                    ->setTargetDevice("vda")
                ;
            })
            ->addQEMUGuestAgentChannel()
            ->disableMemoryBalloon()
            ;
</pre>

**Comment by yzslab** [comment]
Hi,
In my system, I don't get the exists domain specifications from its XML, I store the them in the database. Because libvirt will add more configuration based on your XML pass to it, such as the "address" element inside the "disk" element, changing disk target only without changing its address will cause some problem.

The libvirt_domain_define_xml() can be used to update domain too. What you need to do is keeping the uuid value in the XML unchanged. Storing the uuid of your domain when your define it for the first time: 
```
$uuid = ...; // Generate uuid for this new domain
...
$domainXML = new YunInternet\Libvirt\Configuration\Domain(...);
$domainXML->setUUID($uuid);
...
$connection = new YunInternet\Libvir\Connection(...);
$domain = $connection->domainDefineXML($domainXML->getXML());
// then store the $uuid
```
If you omit $domainXML->setUUID($uuid), libvirt will generate one for you automatically, you can get it via $domain->libvirt_domain_get_uuid_string().
When I need to update the domain, I get its specifications and uuid from database, build a new XML with that uuid and define it:
```
$uuid = ...; // Get uuid from database
...
$domainXML = new YunInternet\Libvirt\Configuration\Domain(...);
$domainXML->setUUID($uuid);
...
$connection = new YunInternet\Libvir\Connection(...);
$domain = $connection->domainDefineXML($domainXML->getXML());
```

**Comment by yzslab** [comment]
libvirt_domain_attach_device() can be used to add disk too: 
```
        $diskConfigurationBuilder = new \YunInternet\Libvirt\Configuration\Domain\Device\Disk("volume", "disk", new \SimpleXMLElement("<disk/>"));
        $diskConfigurationBuilder
            ->setDriver("qemu")
            ->setDriverType("qcow2")
            ->volumeSource(Storage::storagePoolName(), $uniqueIdOrStorageVolume)
            ->setTargetDevice($busCounter->formattedName($busText))
            ->setTargetBus($busText)
            ->setValue(Storage::DEFAULT_SCSI_VENDOR)
            ->setValue(Storage::DEFAULT_SCSI_PRODUCT)
        ;
        $diskConfigurationBuilder->serial()->setValue($uniqueIdOrStorageVolume);
        ...
        ...->getDomain()->libvirt_domain_attach_device($diskConfigurationBuilder->getXML(), $flag); // $flag is VIR_DOMAIN_AFFECT_CONFIG, VIR_DOMAIN_DEVICE_MODIFY_LIVE or VIR_DOMAIN_AFFECT_LIVE
```
The code are copied from my system, there are some functions or variable not exists in this project, but it can tell you how to add devices.

**Comment by inode64** [comment]
It was to make a backup system and when the disks are network (glusterfs) it is necessary to know the current location to create the snapshot disk in the same location.
And also to create a control panel to manage kvm machines

**Comment by yzslab** [comment]
> It was to make a backup system and when the disks are network (glusterfs) it is necessary to know the current location to create the snapshot disk in the same location.
> And also to create a control panel to manage kvm machines

I did not implement an easy interface to obtain the parameters that you need, if you are willing to implement it, it will be great. 
And you are free to enhance this php package, enhancing it is always a great job.

I think place "getDisk()" in ["YunInternet\Libvirt\Domain"](https://github.com/yzslab/php-libvirt-client/blob/master/src/YunInternet/Libvirt/Domain.php) is better.

**Comment by yzslab** [comment]
> It was to make a backup system and when the disks are network (glusterfs) it is necessary to know the current location to create the snapshot disk in the same location.
> And also to create a control panel to manage kvm machines

There is a method YunInternet\Libvirt\Domain::libvirt_domain_update_device(), which can be used to update single device without define the domain again.

**Comment by inode64** [comment]
OK, but I had to know where the current disk is stored to take a snapshot.
I was performing a function in \libvirt\domain.php but I thought it better to take advantage of your current structure.

**Comment by inode64** [comment]
I have understood how it has done, I had never used reflection or SimpleXMLElement.
You have been a great help
